### ISSUE TITLE
Show pause button on hover

### ISSUE THREAD

**Issue by David-Mulder** [gorork/paper-audio-player#8]
Hovering anywhere on the element should probably show the pause button as it can be somewhat confusing otherwise for the user to find the pause button.

**Comment by gorork** [comment]
It shouldn't display pause icon on hovering anywhere, because it'll be even more confusing to not being able to pause it anywhere. 

I totally agree with you on the issue with the pause icon not being visible. I've been thinking about it myself for a while. I believe I found a friendly solution for this, and going to push it soon.

**Comment by David-Mulder** [comment]
@gorork Did you actually check the pull request :/

**Comment by David-Mulder** [comment]
@gorork Showing the pause icon is quite different from clicking it I believe though~

**Comment by gorork** [comment]
@David-Mulder Showing it on hover would indicate that user can click right there to pause an audio, which wouldn't happen. Instead, it would fast-forward an audio to that point, which wasn't the user intention at all. That makes the experience really messy.

Actually, the very first version of the player showed the pause icon on hovering anywhere, because it really could pause an audio on click anywhere on the player. :) However, after implementing the progress search feature when user can click anywhere to fast-forward an audio, it had to go away, because it was confusing for users.

I closed this issue, since I pushed some changes yesterday that allow users to always see play/pause icons, which solves it in user-friendly way.
